load("@rules_kotlin//kotlin:core.bzl", "define_kt_toolchain", "kt_kotlinc_options", "kt_compiler_plugin")
load("@rules_kotlin//kotlin:jvm.bzl", "kt_javac_options")

define_kt_toolchain(
    name = "kotlin_toolchain",
    api_version = "2.0",
    language_version = "2.0",
)

kt_kotlinc_options(
    name = "k17",
    jvm_target = "17",
    x_enable_incremental_compilation = True,
    x_optin = [],
    visibility = ["//:__subpackages__"],
)

kt_javac_options(
    name = "j17",
    release = "17",
    visibility = ["//:__subpackages__"],
)

kt_compiler_plugin(
    name = "jetpack_compose_compiler_plugin",
    id = "androidx.compose.compiler",
    target_embedded_compiler = True,
    visibility = ["//:__subpackages__"],
    deps = [
        "@maven//:org_jetbrains_kotlin_kotlin_compose_compiler_plugin_embeddable",
    ],
)
